# Site settings
name: Nikolaus Fricker
email: nikofricker@hotmail.com
url: url
description: "My blog for CISS 497"
author: "Nikolaus Fricker"
title: "CISS 497 Weekly Blog"
permalink: pretty
baseurl: /CISS497blog

# social
github:
  username: https://github.com/Wafflez4Reason

#twitter:
#  username: username
